# seeing the world
location=['italy', 'dubai','phillipines', 'greece']
print(location)
print("\n")
print(sorted(location))
print("\nthe original list:" )
print(location)
print("\n")
print(sorted(location, reverse=True))
print(location)
print("\n")
location.reverse()
location.reverse()
print(location)
print("\n")
location.sort()
print(location)
location.sort(reverse=True)
print(location)
